version: '3.4'

services:
  db.catalog:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  db.basket:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  db.discount:
    container_name: discountdb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/





  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@app.com
      - PGADMIN_DEFAULT_PASSWORD=pass123
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin


  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - portainer_data:/data 
   
      


  api.catalog:
    container_name: api.catalog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://db.catalog:27017"
    ports:
      - "3500:80"
    depends_on:
       - db.catalog

  api.basket:
    container_name: api.basket
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RedisSettings:ConnectionString=db.basket:6379"
      - "GrpcSettings:DiscountUrl=http://grpc.discount"
    ports:
      - "3501:80"
    depends_on: 
      - db.basket

  api.discount:
    container_name: api.discount
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "PostgresSettings:ConnectionString=Server=host.docker.interal;Port=5432;Database=DiscountDb;User Id=admin;Password=admin123;"
    ports:
      - "3502:80"
    depends_on:
      - db.discount


  grpc.discount:
    container_name: grpc.discount
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "PostgresSettings:ConnectionString=Server=host.docker.interal;Port=5432;Database=DiscountDb;User Id=admin;Password=admin123;"
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "3503:80"
      - "3504:443"
    depends_on:
      - db.discount
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
