version: '3.4'

services:
  db.catalog:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  db.basket:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - portainer_data:/data 
      
  api.catalog:
    container_name: api.catalog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://db.catalog:27017"
    ports:
      - "3500:80"
    depends_on:
       - db.catalog

  api.basket:
    container_name: api.basket
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RedisSettings:ConnectionString=db.basket:6379"
    ports:
      - "3501:80"
    depends_on: 
      - db.basket
