version: '3.4'

services:
  db.catalog:
    image: mongo
  
  db.basket:
    image: redis:alpine

  db.discount:
    image: postgres


  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce



  api.catalog:
    image: ${DOCKER_REGISTRY-}apicatalog
    build:
      context: .
      dockerfile: Services/Catalog/Api.Catalog/Dockerfile

  api.basket:
    image: ${DOCKER_REGISTRY-}apibasket
    build:
      context: .
      dockerfile: Services/Basket/Api.Basket/Dockerfile

  api.discount:
    image: ${DOCKER_REGISTRY-}apidiscount
    build:
      context: .
      dockerfile: Services/Discount/Api.Discount/Dockerfile

  grpc.discount:
    image: ${DOCKER_REGISTRY-}grpcdiscount
    build:
      context: .
      dockerfile: Services/Discount/gRPC.Discount/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:


